version: '3.6'
#
services:
  irissvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irisdg
    restart: always
    
    ports:
    # superserver default port 
    - "51780:1972"
    # webserver/management portal port
    - "52780:52773"
    
    environment:
    - TZ=JST-9