version: '3.7'
#
services:
  irissvc:
    build:
      context: ./build
      args:
        COMMIT_ID: ${COMMIT_ID}
    image: wolfman0719/irisdg:demo
    init: true
    hostname: myiris
    
    ports:
    # superserver default port 
    - "51780:51773"
    # webserver/management portal port
    - "52780:52773"
    
    environment:
    - TZ=JST-9