version: '3.6'
#
services:
  irissvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irisdg
    restart: always
    command: --check-caps false
    ports:
    # superserver default port 
    - "51773:1972"
    # webserver/management portal port
    - "52773:52773"
    
    environment:
    - TZ=JST-9
